Added command line argument to restrict the number of rows processed
all-of-us/aou-ehr-file-check pull request #31
Opened 2023-03-02 21:34 UTC by jp3477

2023-03-02 22:06 UTC, nishanthpp93 requested changes
Suggested some improvements. Let me know if you have any questions.

2023-03-02 22:06 UTC, nishanthpp93 commented on omop_file_validator.py
> +                        help="Number of rows to validate per file.")
I would suggest using only one arg for this
```suggestion
    parser.add_argument('-r',
                        '--restrict',
                        action='store',
                        required=False,
                        help="Number of rows to restrict for validation per file. e.g. --restrict 1000 for only validating the first 1000 lines")
```

2023-03-02 22:06 UTC, nishanthpp93 commented on omop_file_validator.py
> +                        n_rows=args.n_rows)
You can use only one param here. `args.restrict` will be the number of rows to be validated. If None, skip restriction.
```suggestion
    evaluate_submission(settings.csv_dir,
                        restrict=args.restrict)
```

2023-03-02 22:06 UTC, nishanthpp93 commented on omop_file_validator.py
> +                                     str(idx),
Is this going to change the line number?

2023-03-02 22:06 UTC, nishanthpp93 commented on omop_file_validator.py
> +                break
This will become 
```suggestion
            if restrict and idx - 1 > restrict:
                break
```

2023-04-07 16:05 UTC, jp3477 commented
@nishanthpp93 Sorry it took me so long to get to this. I removed the n_rows argument. Can you explain your question about the line number though?

2023-04-07 21:24 UTC, nishanthpp93 approved these changes
Looks good! I would suggest asking a site test this too

2023-04-07 21:24 UTC, nishanthpp93 commented on omop_file_validator.py
> -        json_list = list(f)
Nice, this may improve memory utilization

2023-06-12 18:54 UTC, merged